name: Update

on:
  schedule:
    - cron: "0 23,5,11 * * *"

env:
  GITHUB_USER_NAME: guidons-master
  GITHUB_USER_EMAIL: guidons.tech@gmail.com
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run
        env:
          TOKEN: ${{ secrets.TOKEN }}
          WX: ${{ secrets.WX }} 
        run: |
          python tracker.py
          
      - name: Update README.md
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Github Action Update"
          files: README.md README_ZH.md data/cache.json data/data.json
          rebase: 'true'
          name: ${{ env.GITHUB_USER_NAME }}
          email: ${{ env.GITHUB_USER_EMAIL }}
